### PR TITLE
burxonov shukurullo

### PR DESCRIPTION
**Pull request by burxonovsh**

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
good code but still you have an issue on your Makefile
pls try to solve it

**Comment by burxonovsh** [comment]
thank you for preview can you tell me about issue where is it 

> good code but still you have an issue on your Makefile pls try to solve it


thank you for review can you tell me about issue where is it

**Comment by burxonovsh** [comment]
> good code but still you have an issue on your Makefile pls try to solve it


thank you for review can you tell me about issue where is it

**Comment by simple-lemon** [comment]
Makefile da tab larni qoyib chiqing 
Etibor bering bazida IDE lar (VS code ....) TAB ni probel ga almashtirib qoyadi shuni to'g'irlashni yo'lini toping

**Pull request closed without merging**
