### PR TITLE
my_ngram.c

### PR DESCRIPTION
**Pull request by burxonovsh**

### CODE REVIEW

**Comment by burxonovsh** [comment]
hammasini bitta qilib tasha olmadim

**Review by simple-lemon — CHANGES_REQUESTED** [review]
Makefile , README fayllariniham qoshib tashlang!!!

**Comment by simple-lemon** [comment]
branch yaratganingizda ism familiya toliq yozilishi shart!!!!!!!!!!!!

**Comment by burxonovsh** [comment]
> Makefile , README fayllariniham qoshib tashlang!!!

hop

**Pull request closed without merging**
